# Generated by Django 4.0.4 on 2022-04-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=15)),
                ('API_KEY', models.CharField(max_length=65)),
                ('API_SECRET_KEY', models.CharField(max_length=65)),
                ('protecionDatos', models.BooleanField()),
                ('avisoTelegram', models.TextField()),
            ],
        ),
    ]
