# Generated by Django 4.0.4 on 2022-05-01 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuariosApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
    ]
