# Generated by Django 4.0.4 on 2022-05-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuariosApp', '0002_alter_usuarios_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=15)),
                ('API_KEY', models.CharField(max_length=65)),
                ('API_SECRET_KEY', models.CharField(max_length=65)),
                ('protecionDatos', models.BooleanField()),
                ('avisoTelegram', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
            },
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
